## SVM klasifikasi

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
%matplotlib notebook

In [2]:
dataset = pd.read_csv('clustered_analysis.csv')

In [3]:
dataset.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)  \
0           1    Male   19                  15                      39   
1           2    Male   21                  15                      81   
2           3  Female   20                  16                       6   
3           4  Female   23                  16                      77   
4           5  Female   31                  17                      40   

   Segment   
0         5  
1         4  
2         5  
3         4  
4         5

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
 5   Segment                 200 non-null    int64 
dtypes: int64(5), object(1)
memory usage: 9.5+ KB


In [5]:
X = dataset.iloc[:, 2:6]
X.head()

Age  Annual Income (k$)  Spending Score (1-100)  Segment 
0   19                  15                      39         5
1   21                  15                      81         4
2   20                  16                       6         5
3   23                  16                      77         4
4   31                  17                      40         5

In [6]:
X = pd.get_dummies(X)

In [7]:
X = X.values
X #cetak X

array([[ 19,  15,  39,   5],
       [ 21,  15,  81,   4],
       [ 20,  16,   6,   5],
       [ 23,  16,  77,   4],
       [ 31,  17,  40,   5],
       [ 22,  17,  76,   4],
       [ 35,  18,   6,   5],
       [ 23,  18,  94,   4],
       [ 64,  19,   3,   5],
       [ 30,  19,  72,   4],
       [ 67,  19,  14,   5],
       [ 35,  19,  99,   4],
       [ 58,  20,  15,   5],
       [ 24,  20,  77,   4],
       [ 37,  20,  13,   5],
       [ 22,  20,  79,   4],
       [ 35,  21,  35,   5],
       [ 20,  21,  66,   4],
       [ 52,  23,  29,   5],
       [ 35,  23,  98,   4],
       [ 35,  24,  35,   5],
       [ 25,  24,  73,   4],
       [ 46,  25,   5,   5],
       [ 31,  25,  73,   4],
       [ 54,  28,  14,   5],
       [ 29,  28,  82,   4],
       [ 45,  28,  32,   5],
       [ 35,  28,  61,   4],
       [ 40,  29,  31,   5],
       [ 23,  29,  87,   4],
       [ 60,  30,   4,   5],
       [ 21,  30,  73,   4],
       [ 53,  33,   4,   5],
       [ 18,  33,  92,   4],
       [ 49,  

In [8]:
Y = dataset.iloc[:, -1].values ## mengambil label yang telah dibuat oleh K-Means clustering
Y #cetak Y

array([5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4,
       5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 0, 4, 0, 3,
       5, 4, 0, 3, 3, 3, 0, 3, 3, 0, 0, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 3,
       0, 0, 3, 3, 0, 0, 0, 0, 0, 3, 0, 3, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3,
       3, 0, 0, 3, 0, 3, 3, 3, 0, 3, 0, 3, 3, 0, 0, 3, 0, 3, 0, 0, 0, 0,
       0, 3, 3, 3, 3, 3, 0, 0, 0, 0, 3, 3, 3, 1, 3, 1, 2, 1, 2, 1, 2, 1,
       3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       2, 1], dtype=int64)

## Split data

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=.25, random_state = 19)

array([3, 1, 1, 2, 1, 2, 3, 1, 0, 0, 1, 3, 5, 3, 4, 0, 3, 3, 4, 0, 1, 5,
       5, 3, 1, 1, 5, 1, 1, 3, 3, 1, 0, 0, 1, 1, 3, 4, 1, 5, 0, 3, 3, 5,
       0, 2, 0, 0, 1, 3, 2, 2, 4, 3, 3, 2, 2, 0, 1, 3, 0, 4, 2, 2, 1, 2,
       2, 0, 4, 5, 2, 3, 1, 1, 1, 0, 0, 4, 0, 0, 3, 2, 2, 0, 2, 0, 0, 2,
       1, 2, 3, 3, 3, 1, 1, 4, 5, 0, 1, 0, 5, 3, 3, 2, 2, 1, 3, 4, 1, 1,
       1, 4, 5, 3, 2, 3, 2, 0, 0, 0, 4, 0, 3, 3, 0, 0, 5, 4, 0, 4, 4, 1,
       0, 0, 0, 5, 3, 1, 2, 5, 2, 0, 1, 0, 3, 4, 2, 0, 0, 3], dtype=int64)

## Training set menggunakan metode linier SVM

In [11]:
from sklearn.svm import LinearSVC # digunakan untuk classifier SVM
from sklearn import svm

In [12]:
svc = LinearSVC()

In [13]:
svc.fit(X_train, Y_train)

C:\Users\Asus\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [14]:
# hasil output model terhadap validation set disimpan kedalam variable Y_pred yang kemudian dicocokan dengan label yang disimpan dengan variable Y_test
Y_pred = svc.predict(X_test)
Y_pred

array([0, 2, 4, 3, 4, 3, 2, 5, 2, 1, 4, 3, 5, 2, 3, 3, 0, 3, 2, 1, 0, 0,
       0, 1, 2, 4, 0, 1, 3, 2, 4, 3, 5, 5, 5, 2, 5, 1, 0, 1, 2, 4, 0, 2,
       3, 2, 5, 3, 5, 0], dtype=int64)

## Hitung accuracy

In [15]:
from sklearn.metrics import classification_report, confusion_matrix

In [16]:
print(classification_report(Y_test.reshape(-1, 1), Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.75      0.86         8
           2       1.00      1.00      1.00        11
           3       0.70      1.00      0.82         7
           4       1.00      0.86      0.92         7
           5       1.00      1.00      1.00         8

    accuracy                           0.94        50
   macro avg       0.95      0.93      0.93        50
weighted avg       0.96      0.94      0.94        50



In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
print('Cross val: ', cross_val_score(svc, Y_test.reshape(-1, 1), Y_pred, cv= 7))
print('Accuracy : ', np.mean(cross_val_score(svc, Y_test.reshape(-1, 1), Y_pred)))

Cross val:  [0.5        0.85714286 0.57142857 0.57142857 0.71428571 0.85714286
 0.42857143]
Accuracy :  0.7


C:\Users\Asus\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=7.
  warnings.warn(("The least populated class in y has only %d"
